# Generated by Django 2.1.2 on 2018-11-24 05:25

import admin_rjf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk', models.CharField(max_length=200)),
                ('post_thumbnail', models.ImageField(default='default.jpg', upload_to=admin_rjf.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('google_plus', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('project_dan_asal', models.CharField(max_length=100)),
                ('komentar', models.TextField()),
            ],
        ),
    ]
