# Generated by Django 2.1.2 on 2018-11-24 06:23

import admin_rjf.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rjf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk_Unggulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='default.jpg', upload_to=admin_rjf.models.path_and_rename)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gallery_foto',
            name='kategori',
            field=models.CharField(choices=[('backdrop', 'Draft'), ('bedroom', 'Bedroom'), ('meja_meeting', 'Meja Meeting'), ('front_office', 'Front Office'), ('Rak', 'Rak'), ('tangga', 'Tangga')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
