# Generated by Django 2.1.2 on 2018-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rjf', '0002_auto_20181124_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_foto',
            name='kategori',
            field=models.CharField(choices=[('backdrop', 'Back Drop'), ('bedroom', 'Bedroom'), ('meja_meeting', 'Meja Meeting'), ('front_office', 'Front Office'), ('rak', 'Rak'), ('tangga', 'Tangga')], max_length=200),
        ),
    ]
