# Generated by Django 2.1.2 on 2018-12-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rjf', '0006_profil_nama_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomentarSaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pesan', models.TextField()),
            ],
        ),
    ]
